openapi: 3.0.1
info:
  title: Named-Entity Recognition JP
  description: |+
      This NLP microservice locates and classifies the named-entity classes from input unstructured Japanese text.</br>
      The named-entity classes extracted are academia, animals, fictional characters, colors, date, diseases, events, facilities, food, geopolitical entities, langauges law, locations, media works, measurements, money, identity groups, natural objects, ordinals, offences, organizations, percentage, people, products, quantities, sports, time, titles, vehicles, works of art and weapons.</br>
      This microservice automatically extracts structured information from unstructured text data such as chat logs, emails, news articles, etc.</br>
      The input text **should not exceed 5000 characters**.
  
  version: '2.0.0'
  x-additionalinfo: |+
    Suggested Use Cases:
    - Extract structured pre-defined information from text.</br>
    - Insights from online customers - extract structured information from unstructured text data such as chat logs, emails, news articles, etc. to find and label fields within a document and then apply sentiment analysis to understand customer opinions to find actionable product and UX insights.</br>
    - Entity analysis - identify entities within documents, including receipts, invoices, and contracts; and label them by types such as date, person, contact information, organization, location, events, products, and media.
  x-subscribelink: named-entity_recognition_jp
  x-apitype: small file
  x-apitypedescription: |+
    Fast | Single-Call | 5000 characters/Call
  x-inputfilelimit: |+
    Process up to 5000 characters per API call.
  x-responsetime: |+
    Response rate is fast due to small data transfer per call made.
  x-billingmethod: |+
    The API is billed by per request.
  x-notes: |+
    Limit cannot exceed 5000 characters.
  x-apidetailsdesc: |+
    Locates and Classifies named-entities classes from unstructured Japanese text.
servers:
  - url: 'https://apis.sentient.io'
tags:
- name: "v2.0.0"
  description: "Published Date - Jun 03, 2022"
paths:
  /microservices/nlp/japanesener/v2/getpredictions:
    post:
      tags:
        - v2.0.0
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                message: Successfully Processed
                results:
                  ordinal:
                  - entity: 30弾
                    start: 0
                    end: 3
                  other:
                  - entity: 険所コホ特室りょ
                    start: 16
                    end: 24
                  person:
                  - entity: くぼ
                    start: 24
                    end: 26
                  - entity: 壮
                    start: 74
                    end: 75
                  - entity: 琢紫
                    start: 83
                    end: 85
                  - entity: ナユ
                    start: 98
                    end: 100
                  artefact:
                  - entity: 都合ヘラアニ限
                    start: 26
                    end: 33
                  - entity: 議帳
                    start: 104
                    end: 106
                  quantity:
                  - entity: 2稿
                    start: 33
                    end: 35
                  - entity: 8口
                    start: 79
                    end: 81
                  - entity: 受1
                    start: 108
                    end: 110
                  measurement:
                  - entity: 百経
                    start: 92
                    end: 94
                  - entity: '56'
                    start: 130
                    end: 132
                  organization:
                  - entity: 左成相態
                    start: 172
                    end: 176

                status: Success
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '413':
          description: Payload Too Large
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded' 
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
        required: true
      security:
        - APIAuthorizer: []
components:
  schemas:
    success:
      type: object
      properties: 
        results:
          type: object
          example: { "<Json": "Object>" }
          description: Json Object of returned results
          properties: 
            academia:
              x-name: academia
              type: array
              example: 
              - entity: 日本流
                start: 128
                end: 131
              description: "Academic field, school, method of art or science"   
            animal:
              x-name: animal
              type: array
              example: 
              - entity: ミツバチ
                start: 56
                end: 60
              description: "Animals (includes insects, birds, reptiles, mammals and fishes, etc)"
            character:
              x-name: character
              type: array
              example: 
              - entity: トトロ
                start: 16
                end: 19
              description: "A name of a fictional character. This includes the characters of a story.A name of a fictional animal that appear in more than one work, like \"werewolf\" is not included here but in natural_object Category. Other fictional animal that only appear in a specific work, like \"Pikachu\", is included."    
            color:
              x-name: color
              type: array
              example: 
              - entity: 赤
                start: 122
                end: 123
              - entity: 青
                start: 124
                end: 125
              - entity: 緑
                start: 126
                end: 127
              description: "Color" 
            date:
              x-name: date
              type: array
              example: 
              - entity: 11日
                start: 6
                end: 9
              - entity: 2019年
                start: 123
                end: 128
              description: "Expression of a date"   
            disease:
              x-name: disease
              type: array
              example: 
              - entity: 天然痘ウイルス
                start: 159
                end: 166
              description: "Disease or injury" 
            event:
              x-name: event
              type: array
              example:
              - entity: 世界経済フォーラム
                start: 222
                end: 231
              description: "Event, festival, occasion or phenomenon"       
            facility:
              x-name: facility
              type: array
              example:
              - entity: 仁王門
                start: 56
                end: 60
              description: "Place or building that provides a particular service (including hotels, airports, stations, etc) "    
            food:
              x-name: food
              type: array
              example:
              - entity: すし
                start: 0
                end: 2
              description: "Food, dish or drink"    
            geopolitical:
              x-name: geopolitical
              type: array
              example:
              - entity: 青島
                start: 193
                end: 196
              description: "Geopolitical entitity (including countries, cities, states, etc)"  
            identity_groups:
              x-name: identity_groups
              type: array
              example:
              - entity: 日本人
                start: 396
                end: 399
              description: "Nationalities, religious, ethnic and political groups"  
            language:
              x-name: language
              type: array
              example:
              - entity: 英語
                start: 107
                end: 109
              description: "Language, language family or dialect"  
            law:
              x-name: law
              type: array
              example:
              - entity: 9条
                start: 137
                end: 139
              description: "Law, statute, article or order"  
            location:
              x-name: location
              type: array
              example:
              - entity: サンフランシスコ
                start: 349
                end: 357
              - entity: ドイツ
                start: 62
                end: 65
              description: "Place or location (including non-geopolitical entities)"  
            media:
              x-name: media
              type: array
              example:
              - entity: 月組スター
                start: 0
                end: 5
              description: "Physical media (e.g. print, video record), production (e.g. animation, music video, television advertisement, television show, movie) or broadcast programs (e.g. television & radio)" 
            measurement:
              x-name: measurement
              type: array
              example: 
              - entity: 百経
                start: 92
                end: 94
              description: "Various measurement units (including length, weight, area, volume, temperature, etc)" 
            money:
              x-name: money
              type: array
              example:
              - entity: 6千万円
                start: 786
                end: 790
              description: "Currency or physical representation of money (e.g. bill, banknote, or coin)" 
            natural_object:
              x-name: natural_object
              type: array
              example:
              - entity: 竹
                start: 282
                end: 289
              description: "Natural object or material (including chemical compounds, mineral and living things)"   
            ordinal:
              x-name: ordinal
              type: array
              example: 
              - entity: 30弾
                start: 0
                end: 3
              description: "Expression of order (e.g. \"first\", \"second\", etc)" 
            offense:
              x-name: offense
              type: array
              example:
              - entity: 痴漢
                start: 0
                end: 2
              description: "Act of crime or rap"  
            organization:
              x-name: organization
              type: array
              example: 
              - entity: 左成相態
                start: 172
                end: 176
              description: "Companies, agencies or institutions" 
            other:
              x-name: other
              type: array
              example: 
              - entity: 険所コホ特室りょ
                start: 16
                end: 24
              description: "All other miscellaneous classes"  
            percent:
              x-name: percent
              type: array
              example:
              - entity: 約半分
                start: 274
                end: 277
              description: "Percentage" 
            person:
              x-name: person
              type: array
              example: 
              - entity: くぼ
                start: 24
                end: 26
              - entity: 壮
                start: 74
                end: 75
              - entity: 琢紫
                start: 83
                end: 85
              - entity: ナユ
                start: 98
                end: 100
              description: "People, including fictional" 
            product:
              x-name: product
              type: array
              example: 
              - entity: 都合ヘラアニ限
                start: 26
                end: 33
              - entity: 議帳
                start: 104
                end: 106
              description: "Thing, object or product produced by human beings"
            quantity:
              x-name: quantity
              type: array
              example: 
              - entity: 2稿
                start: 33
                end: 35
              - entity: 8口
                start: 79
                end: 81
              description: "Expression of count or quantification" 
            sports:
              x-name: sports
              type: array
              example: 
              - entity: サッカー
                start: 1
                end: 5
              description: "A name of a sport in which the superiority of the player can be judged."
            time:
              x-name: time
              type: array
              example: 
              - entity: 江戸時代
                start: 174
                end: 176
              description: "Expression that refers to a point in time or period" 
            title:
              x-name: title
              type: array
              example: 
              - entity: 株主
                start: 174
                end: 176
              description: "Name of title, position, occupation or position that indicates person's status"
            vehicle:
              x-name: vehicle
              type: array
              example: 
              - entity: ジャガー
                start: 232
                end: 236
              - entity: ポルシェ
                start: 237
                end: 241
              description: "Vehicle, including train, ship and aircraft" 
            work_of_art:
              x-name: work_of_art
              type: array
              example: 
              - entity: 天空の城ラピュタ
                start: 1
                end: 9
              description: "Music, songs, books, paintings and any other form of written or verbal work" 
            weapon:
              x-name: weapon
              type: array
              example: 
              - entity: 核
                start: 679
                end: 680
              description: "Weapon, arm or armament" 
                          
                              
        message:
          type: string
          example: Successfully Processed
          description: Description of the API status
        status:
          type: string
          example: Success
          description: The status of the API call - success/failure  
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure 
    invalidinput:
      type: object
      properties:
        message:
          type: string
          example: Invalid Input
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties: 
        v2.0.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Jun 03, 2022
              x-details: Updated version release v1.0, entity positions returned
              description: Latest Version
        v1.0.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Sep 30, 2020
              x-details: Updated version release v1.0
              description: Version 1 release
        v0.1.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - May 15, 2020
              x-details: Initial version release
              description: Archived
    input:
      type: object
      required:
        - text
      properties:
        text:
          x-name: text
          type: string
          default: true
          example: 30弾ソイキ昇機マ了映だ店原いひ険所コホ特室りょくぼ都合ヘラアニ限2稿タチケア迷芸歌セ利講ルねひ詳績めかをぶ観提メエ府木ホフタ分不写ひフ妹検らし器増壮憶クわ。8口アユ琢紫ヨ理特ゆほス見百経イス図退ナユ介精しぜ議帳モテ受1中コハ載北早ぎのりや載裁風力壌ひろふ。運56済ぞ下写報スや来際おっはの学要ヘ手米真社つみよや非央で野館き肉待づぜフ次睡ルをが左成相態万えやろ。
          description: |+
            Input text.
            
            Supported formats: ASCII only

        return_entity_position:
          x-name: return_entity_position
          type: boolean
          default: false
          example: true
          description: |+
            Boolean value indicating whether entity position needs to be returned or not. Default value is True.
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
