openapi: 3.0.1
info:
  title: Receipt Scanner
  description: |+
      This Computer Vision microservice takes in receipts and extracts meaningful and structured data, including the total amount, tax amount, date, and merchant name. </br>
      The API will return a JSON containing all the extracted data, along with details of where that information was on the page, confidence values, and the coordinates containing the data field in the original document.</br>
      This API is optimized for computer-generated PDFs but also supports pdf scans, png, jpeg, tiff, jfif, and docx files.
  version: '0.2.0'
  x-subscribelink: receipt_scanner
  x-apitype: small file
  x-apitypedescription: |+
    Fast | Single-Call | 10MB/Call
  x-inputfilelimit: |+
    Process up to 10MB of data per API call.
  x-responsetime: |+
    Response rate is fast due to small data transfer per call made.
  x-billingmethod: |+
    The API is billed by per request.
  x-notes: |+
    File size cannot exceed 10 MB.
  x-apidetailsdesc: |+
    Extracts to meaningful and structured data from Receipt docs.
servers:
  - url: 'https://dev-apis.sentient.io'
tags:
- name: "v0.2.0"
  description: "Published Date - Sep 05, 2022"
paths:
  /microservices/cv/scanreceipt/v0/getresults:
    post:
      tags:
        - v0.2.0
      responses:
        '200':
          description: success response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/success'
              example:
                message: Successfully Processed
                results:
                  scanDocuments:
                    data:
                      AccountName:
                        UICategory: Payment Instructions
                        UIName: Account Name
                        UIType: Text
                        matches:
                        - keyword: 
                          match: 
                          matchmulti: 
                          page: 
                          value: 
                      AccountNumber:
                        UICategory: Payment Instructions
                        UIName: Account Number
                        UIType: Text
                        matches:
                        - keyword: 
                          match: 
                          matchmulti: 
                          page: 
                          value: 
                      BigBoxes:
                      - box:
                        - 106
                        - 134
                        - 385
                        - 174
                        - 245.5
                        - 154
                        - East Repair Inc.
                        - East Repair Inc.
                        page: 0
                      - box:
                        - 1148
                        - 129
                        - 1308
                        - 171
                        - 1228
                        - 150
                        - RECEIPT
                        - RECEIPT
                        page: 0
                      - box:
                        - 102
                        - 208
                        - 322
                        - 273
                        - 212
                        - 240.5
                        - |-
                          1912 Harvest Lane
                          New York, NY 12210
                        - |-
                          1912 Harvest Lane
                          New York , NY 12210
                        page: 0
                      - box:
                        - 1232
                        - 455
                        - 1307
                        - 479
                        - 1269.5
                        - 467
                        - US-001
                        - US-001
                        page: 0
                      - box:
                        - 102
                        - 452
                        - 322
                        - 591
                        - 212
                        - 521.5
                        - |-
                          Bill To
                          John Smith
                          2 Court Square
                          New York, NY 12210
                        - |-
                          Bill To
                          John Smith
                          2 Court Square
                          New York , NY 12210
                        page: 0
                      - box:
                        - 529
                        - 454
                        - 766
                        - 595
                        - 647.5
                        - 524.5
                        - |-
                          Ship To
                          John Smith
                          3787 Pineview Drive
                          Cambridge, MA 12210
                        - |-
                          Ship To
                          John Smith
                          3787 Pineview Drive
                          Cambridge , MA 12210
                        page: 0
                      - box:
                        - 972
                        - 452
                        - 1113
                        - 531
                        - 1042.5
                        - 491.5
                        - |-
                          Receipt #
                          Receipt Date
                        - |-
                          Receipt #
                          Receipt Date
                        page: 0
                      - box:
                        - 1193
                        - 500
                        - 1309
                        - 527
                        - 1251
                        - 513.5
                        - 11/02/2019
                        - 11/02/2019
                        page: 0
                      - box:
                        - 1055
                        - 553
                        - 1114
                        - 575
                        - 1084.5
                        - 564
                        - 'PO #'
                        - 'P.O. #'
                        page: 0
                      - box:
                        - 1200
                        - 553
                        - 1310
                        - 576
                        - 1255
                        - 564.5
                        - 2312/2019
                        - 2312/2019
                        page: 0
                      - box:
                        - 1012
                        - 600
                        - 1112
                        - 622
                        - 1062
                        - 611
                        - Due Date
                        - Due Date
                        page: 0
                      - box:
                        - 1193
                        - 600
                        - 1310
                        - 623
                        - 1251.5
                        - 611.5
                        - 26/02/2019
                        - 26/02/2019
                        page: 0
                      - box:
                        - 130
                        - 732
                        - 178
                        - 751
                        - 154
                        - 741.5
                        - QTY
                        - QTY
                        page: 0
                      - box:
                        - 422
                        - 731
                        - 580
                        - 752
                        - 501
                        - 741.5
                        - DESCRIPTION
                        - DESCRIPTION
                        page: 0
                      - box:
                        - 831
                        - 722
                        - 962
                        - 759
                        - 896.5
                        - 740.5
                        - UNIT PRICE
                        - UNIT PRICE
                        page: 0
                      - box:
                        - 1102
                        - 730
                        - 1205
                        - 752
                        - 1153.5
                        - 741
                        - AMOUNT
                        - AMOUNT
                        page: 0
                      - box:
                        - 149
                        - 793
                        - 155
                        - 813
                        - 152
                        - 803
                        - '1'
                        - '1'
                        page: 0
                      - box:
                        - 229
                        - 793
                        - 518
                        - 816
                        - 373.5
                        - 804.5
                        - Front and rear brake cables
                        - Front and rear brake cables
                        page: 0
                      - box:
                        - 911
                        - 793
                        - 981
                        - 814
                        - 946
                        - 803.5
                        - '100.00'
                        - '100.00'
                        page: 0
                      - box:
                        - 1220
                        - 793
                        - 1289
                        - 816
                        - 1254.5
                        - 804.5
                        - '100.00'
                        - '100.00'
                        page: 0
                      - box:
                        - 148
                        - 857
                        - 159
                        - 876
                        - 153.5
                        - 866.5
                        - '2'
                        - '2'
                        page: 0
                      - box:
                        - 229
                        - 852
                        - 463
                        - 884
                        - 346
                        - 868
                        - New set of pedal arms
                        - New set of pedal arms
                        page: 0
                      - box:
                        - 925
                        - 857
                        - 981
                        - 879
                        - 953
                        - 868
                        - '15.00'
                        - '15.00'
                        page: 0
                      - box:
                        - 1231
                        - 856
                        - 1290
                        - 879
                        - 1260.5
                        - 867.5
                        - '30.00'
                        - '30.00'
                        page: 0
                      - box:
                        - 149
                        - 920
                        - 160
                        - 939
                        - 154.5
                        - 929.5
                        - '3'
                        - '3'
                        page: 0
                      - box:
                        - 229
                        - 918
                        - 340
                        - 939
                        - 284.5
                        - 928.5
                        - Labor 3hrs
                        - Labor 3hrs
                        page: 0
                      - box:
                        - 936
                        - 920
                        - 980
                        - 940
                        - 958
                        - 930
                        - '5.00'
                        - '5.00'
                        page: 0
                      - box:
                        - 1233
                        - 920
                        - 1289
                        - 941
                        - 1261
                        - 930.5
                        - '15.00'
                        - '15.00'
                        page: 0
                      - box:
                        - 897
                        - 981
                        - 981
                        - 1003
                        - 939
                        - 992
                        - Subtotal
                        - Subtotal
                        page: 0
                      - box:
                        - 1219
                        - 980
                        - 1288
                        - 1002
                        - 1253.5
                        - 991
                        - '145.00'
                        - '145.00'
                        page: 0
                      - box:
                        - 803
                        - 1042
                        - 980
                        - 1063
                        - 891.5
                        - 1052.5
                        - Sales Tax 6.25%
                        - Sales Tax 6.25%
                        page: 0
                      - box:
                        - 1244
                        - 1042
                        - 1289
                        - 1065
                        - 1266.5
                        - 1053.5
                        - '9.06'
                        - '9.06'
                        page: 0
                      - box:
                        - 872
                        - 1104
                        - 981
                        - 1137
                        - 926.5
                        - 1120.5
                        - TOTAL
                        - TOTAL
                        page: 0
                      - box:
                        - 1172
                        - 1101
                        - 1289
                        - 1140
                        - 1230.5
                        - 1120.5
                        - "$ 154.06"
                        - "$ 154.06"
                        page: 0
                      - box:
                        - 102
                        - 1728
                        - 422
                        - 1801
                        - 262
                        - 1764.5
                        - |-
                          Terms & Conditions
                          Payment is due within 15 days
                        - |-
                          Terms & Conditions
                          Payment is due within 15 days
                        page: 0
                      - box:
                        - 104
                        - 1841
                        - 616
                        - 1871
                        - 360
                        - 1856
                        - 'Please make checks payable to: East Repair Inc.'
                        - 'Please make checks payable to: East Repair Inc.'
                        page: 0
                      BillingAddress:
                        UICategory: Vendor & Customer
                        UIName: Billing Address
                        UIType: Text
                        matches:
                        - keyword:
                          - 102
                          - 452
                          - 322
                          - 591
                          - 212
                          - 521.5
                          - |-
                            Bill To
                            John Smith
                            2 Court Square
                            New York, NY 12210
                          - |-
                            Bill To
                            John Smith
                            2 Court Square
                            New York , NY 12210
                          match: |-
                            John Smith
                            2 Court Square
                            New York, NY 12210
                          matchmulti: Bill To John Smith 2 Court Square New York , NY 12210
                          page: 0
                          value:
                          - 102
                          - 452
                          - 322
                          - 591
                          - 212
                          - 521.5
                          - |-
                            Bill To
                            John Smith
                            2 Court Square
                            New York, NY 12210
                          - |-
                            Bill To
                            John Smith
                            2 Court Square
                            New York , NY 12210
                      CompanyName:
                        UICategory: Vendor & Customer
                        UIName: Vendor Name
                        UIType: Text
                        matches:
                        - keyword:
                          - 106
                          - 134
                          - 385
                          - 174
                          - 245.5
                          - 154
                          - East Repair Inc.
                          - East Repair Inc.
                          match: East Repair Inc.
                          matchmulti: East Repair Inc.
                          page: 0
                          value:
                          - 106
                          - 134
                          - 385
                          - 174
                          - 245.5
                          - 154
                          - East Repair Inc.
                          - East Repair Inc.
                      Currency:
                        UICategory: VAT & Amounts
                        UIName: Currency
                        UIType: Text
                        matches:
                        - keyword:
                          - 872
                          - 1104
                          - 981
                          - 1137
                          - 926.5
                          - 1120.5
                          - TOTAL
                          - TOTAL
                          match: "$"
                          matchmulti: "$ 154.06"
                          page: 0
                          value:
                          - 1172
                          - 1101
                          - 1289
                          - 1140
                          - 1230.5
                          - 1120.5
                          - "$ 154.06"
                          - "$ 154.06"
                      Customer: 
                      DetectedText: 'East Repair Inc. RECEIPT 1912 Harvest Lane New York, NY 12210
                        US-001 Bill To John Smith 2 Court Square New York, NY 12210 Ship To John Smith
                        3787 Pineview Drive Cambridge, MA 12210 Receipt # Receipt Date 11/02/2019
                        PO # 2312/2019 Due Date 26/02/2019 QTY DESCRIPTION UNIT PRICE AMOUNT 1 Front
                        and rear brake cables 100.00 100.00 2 New set of pedal arms 15.00 30.00 3
                        Labor 3hrs 5.00 15.00 Subtotal 145.00 Sales Tax 6.25% 9.06 TOTAL $ 154.06
                        Terms & Conditions Payment is due within 15 days Please make checks payable
                        to: East Repair Inc. '
                      DocSize:
                      - - 2000
                        - 1413
                      Email:
                        UICategory: Vendor & Customer
                        UIName: Email
                        UIType: Text
                        matches:
                        - keyword: 
                          match: 
                          matchmulti: 
                          page: 
                          value: 
                      Freight:
                        UICategory: VAT & Amounts
                        UIName: Freight
                        UIType: Amount
                        matches:
                        - keyword: 
                          match: 
                          matchmulti: 
                          page: 
                          value: 
                      IBAN:
                        UICategory: Payment Instructions
                        UIName: IBAN
                        UIType: Text
                        matches:
                        - keyword: 
                          match: 
                          matchmulti: 
                          page: 
                          value: 
                      InvoiceDate:
                        UICategory: Basic Information
                        UIName: Invoice Date
                        UIType: Date
                        matches:
                        - keyword:
                          - 972
                          - 499
                          - 1113
                          - 531
                          - 1042.5
                          - 515
                          - Receipt Date
                          - Receipt Date
                          match: '2019-11-02'
                          matchmulti: 11/02/2019
                          page: 0
                          value:
                          - 1193
                          - 500
                          - 1309
                          - 527
                          - 1251
                          - 513.5
                          - 11/02/2019
                          - 11/02/2019
                      InvoiceNumber:
                        UICategory: Basic Information
                        UIName: Invoice Number
                        UIType: Text
                        matches:
                        - keyword: 
                          match: 
                          matchmulti: 
                          page: 
                          value: 
                      LineItems:
                      - - 'AMOUNT ':
                          - '100.00'
                          'DESCRIPTION ':
                          - Front and rear brake cables
                          'QTY ':
                          - '1'
                          'UNIT PRICE ':
                          - '100.00'
                        - 'AMOUNT ':
                          - '30.00'
                          'DESCRIPTION ':
                          - New set of pedal arms
                          'QTY ':
                          - '2'
                          'UNIT PRICE ':
                          - '15.00'
                        - 'AMOUNT ':
                          - '15.00'
                          'DESCRIPTION ':
                          - Labor 3hrs
                          'QTY ':
                          - '3'
                          'UNIT PRICE ':
                          - '5.00'
                      LineItems_standardHeader:
                      - - Description: Front and rear brake cables
                          LineAmount: 100
                          Quantity: 1
                          UnitAmount: 100
                        - Description: New set of pedal arms
                          LineAmount: 30
                          Quantity: 2
                          UnitAmount: 15
                        - Description: Labor 3hrs
                          LineAmount: 15
                          Quantity: 3
                          UnitAmount: 5
                      OtherAddress:
                        UICategory: Vendor & Customer
                        UIName: Other Address
                        UIType: Text
                        matches:
                        - keyword: 
                          match: 
                          matchmulti: 
                          page: 
                          value: 
                      OtherDate:
                        UICategory: Basic Information
                        UIName: Other Date
                        UIType: Date
                        matches:
                        - keyword: 
                          match: 
                          matchmulti: 
                          page: 
                          value: 
                      PONumber:
                        UICategory: Vendor & Customer
                        UIName: PO Number
                        UIType: Text
                        matches:
                        - keyword:
                          - 1055
                          - 553
                          - 1114
                          - 575
                          - 1084.5
                          - 564
                          - 'PO #'
                          - 'P.O. #'
                          match: 2312/2019
                          matchmulti: 2312/2019
                          page: 0
                          value:
                          - 1200
                          - 553
                          - 1310
                          - 576
                          - 1255
                          - 564.5
                          - 2312/2019
                          - 2312/2019
                      PaymentDate:
                        UICategory: Basic Information
                        UIName: Payment Date
                        UIType: Date
                        matches:
                        - keyword:
                          - 1012
                          - 600
                          - 1112
                          - 622
                          - 1062
                          - 611
                          - Due Date
                          - Due Date
                          match: '2019-02-26'
                          matchmulti: 26/02/2019
                          page: 0
                          value:
                          - 1193
                          - 600
                          - 1310
                          - 623
                          - 1251.5
                          - 611.5
                          - 26/02/2019
                          - 26/02/2019
                      SenderAddress:
                        UICategory: Vendor & Customer
                        UIName: Vendor Address
                        UIType: Text
                        matches:
                        - keyword:
                          - 106
                          - 134
                          - 385
                          - 174
                          - 245.5
                          - 154
                          - East Repair Inc.
                          - East Repair Inc.
                          match: East Repair Inc.
                          matchmulti: East Repair Inc.
                          page: 0
                          value:
                          - 106
                          - 134
                          - 385
                          - 174
                          - 245.5
                          - 154
                          - East Repair Inc.
                          - East Repair Inc.
                      ShippingAddress:
                        UICategory: Vendor & Customer
                        UIName: Shipping Address
                        UIType: Text
                        matches:
                        - keyword:
                          - 529
                          - 454
                          - 766
                          - 595
                          - 647.5
                          - 524.5
                          - |-
                            Ship To
                            John Smith
                            3787 Pineview Drive
                            Cambridge, MA 12210
                          - |-
                            Ship To
                            John Smith
                            3787 Pineview Drive
                            Cambridge , MA 12210
                          match: |-
                            John Smith
                            3787 Pineview Drive
                            Cambridge, MA 12210
                          matchmulti: Ship To John Smith 3787 Pineview Drive Cambridge , MA 12210
                          page: 0
                          value:
                          - 529
                          - 454
                          - 766
                          - 595
                          - 647.5
                          - 524.5
                          - |-
                            Ship To
                            John Smith
                            3787 Pineview Drive
                            Cambridge, MA 12210
                          - |-
                            Ship To
                            John Smith
                            3787 Pineview Drive
                            Cambridge , MA 12210
                      SmallBoxes:
                      - box:
                        - 106
                        - 134
                        - 385
                        - 174
                        - 245.5
                        - 154
                        - East Repair Inc.
                        - East Repair Inc.
                        page: 0
                      - box:
                        - 1148
                        - 129
                        - 1308
                        - 171
                        - 1228
                        - 150
                        - RECEIPT
                        - RECEIPT
                        page: 0
                      - box:
                        - 105
                        - 208
                        - 302
                        - 241
                        - 203.5
                        - 224.5
                        - 1912 Harvest Lane
                        - 1912 Harvest Lane
                        page: 0
                      - box:
                        - 102
                        - 242
                        - 322
                        - 273
                        - 212
                        - 257.5
                        - New York, NY 12210
                        - New York , NY 12210
                        page: 0
                      - box:
                        - 1232
                        - 455
                        - 1307
                        - 479
                        - 1269.5
                        - 467
                        - US-001
                        - US-001
                        page: 0
                      - box:
                        - 104
                        - 452
                        - 174
                        - 481
                        - 139
                        - 466.5
                        - Bill To
                        - Bill To
                        page: 0
                      - box:
                        - 103
                        - 492
                        - 220
                        - 524
                        - 161.5
                        - 508
                        - John Smith
                        - John Smith
                        page: 0
                      - box:
                        - 103
                        - 527
                        - 262
                        - 559
                        - 182.5
                        - 543
                        - 2 Court Square
                        - 2 Court Square
                        page: 0
                      - box:
                        - 102
                        - 560
                        - 322
                        - 591
                        - 212
                        - 575.5
                        - New York, NY 12210
                        - New York , NY 12210
                        page: 0
                      - box:
                        - 529
                        - 454
                        - 616
                        - 482
                        - 572.5
                        - 468
                        - Ship To
                        - Ship To
                        page: 0
                      - box:
                        - 530
                        - 494
                        - 647
                        - 523
                        - 588.5
                        - 508.5
                        - John Smith
                        - John Smith
                        page: 0
                      - box:
                        - 530
                        - 527
                        - 744
                        - 555
                        - 637
                        - 541
                        - 3787 Pineview Drive
                        - 3787 Pineview Drive
                        page: 0
                      - box:
                        - 529
                        - 559
                        - 766
                        - 595
                        - 647.5
                        - 577
                        - Cambridge, MA 12210
                        - Cambridge , MA 12210
                        page: 0
                      - box:
                        - 1009
                        - 452
                        - 1113
                        - 483
                        - 1061
                        - 467.5
                        - 'Receipt #'
                        - 'Receipt #'
                        page: 0
                      - box:
                        - 972
                        - 499
                        - 1113
                        - 531
                        - 1042.5
                        - 515
                        - Receipt Date
                        - Receipt Date
                        page: 0
                      - box:
                        - 1193
                        - 500
                        - 1309
                        - 527
                        - 1251
                        - 513.5
                        - 11/02/2019
                        - 11/02/2019
                        page: 0
                      - box:
                        - 1055
                        - 553
                        - 1114
                        - 575
                        - 1084.5
                        - 564
                        - 'PO #'
                        - 'P.O. #'
                        page: 0
                      - box:
                        - 1200
                        - 553
                        - 1310
                        - 576
                        - 1255
                        - 564.5
                        - 2312/2019
                        - 2312/2019
                        page: 0
                      - box:
                        - 1012
                        - 600
                        - 1112
                        - 622
                        - 1062
                        - 611
                        - Due Date
                        - Due Date
                        page: 0
                      - box:
                        - 1193
                        - 600
                        - 1310
                        - 623
                        - 1251.5
                        - 611.5
                        - 26/02/2019
                        - 26/02/2019
                        page: 0
                      - box:
                        - 130
                        - 732
                        - 178
                        - 751
                        - 154
                        - 741.5
                        - QTY
                        - QTY
                        page: 0
                      - box:
                        - 422
                        - 731
                        - 580
                        - 752
                        - 501
                        - 741.5
                        - DESCRIPTION
                        - DESCRIPTION
                        page: 0
                      - box:
                        - 831
                        - 722
                        - 962
                        - 759
                        - 896.5
                        - 740.5
                        - UNIT PRICE
                        - UNIT PRICE
                        page: 0
                      - box:
                        - 1102
                        - 730
                        - 1205
                        - 752
                        - 1153.5
                        - 741
                        - AMOUNT
                        - AMOUNT
                        page: 0
                      - box:
                        - 149
                        - 793
                        - 155
                        - 813
                        - 152
                        - 803
                        - '1'
                        - '1'
                        page: 0
                      - box:
                        - 229
                        - 793
                        - 518
                        - 816
                        - 373.5
                        - 804.5
                        - Front and rear brake cables
                        - Front and rear brake cables
                        page: 0
                      - box:
                        - 911
                        - 793
                        - 981
                        - 814
                        - 946
                        - 803.5
                        - '100.00'
                        - '100.00'
                        page: 0
                      - box:
                        - 1220
                        - 793
                        - 1289
                        - 816
                        - 1254.5
                        - 804.5
                        - '100.00'
                        - '100.00'
                        page: 0
                      - box:
                        - 148
                        - 857
                        - 159
                        - 876
                        - 153.5
                        - 866.5
                        - '2'
                        - '2'
                        page: 0
                      - box:
                        - 229
                        - 852
                        - 463
                        - 884
                        - 346
                        - 868
                        - New set of pedal arms
                        - New set of pedal arms
                        page: 0
                      - box:
                        - 925
                        - 857
                        - 981
                        - 879
                        - 953
                        - 868
                        - '15.00'
                        - '15.00'
                        page: 0
                      - box:
                        - 1231
                        - 856
                        - 1290
                        - 879
                        - 1260.5
                        - 867.5
                        - '30.00'
                        - '30.00'
                        page: 0
                      - box:
                        - 149
                        - 920
                        - 160
                        - 939
                        - 154.5
                        - 929.5
                        - '3'
                        - '3'
                        page: 0
                      - box:
                        - 229
                        - 918
                        - 340
                        - 939
                        - 284.5
                        - 928.5
                        - Labor 3hrs
                        - Labor 3hrs
                        page: 0
                      - box:
                        - 936
                        - 920
                        - 980
                        - 940
                        - 958
                        - 930
                        - '5.00'
                        - '5.00'
                        page: 0
                      - box:
                        - 1233
                        - 920
                        - 1289
                        - 941
                        - 1261
                        - 930.5
                        - '15.00'
                        - '15.00'
                        page: 0
                      - box:
                        - 897
                        - 981
                        - 981
                        - 1003
                        - 939
                        - 992
                        - Subtotal
                        - Subtotal
                        page: 0
                      - box:
                        - 1219
                        - 980
                        - 1288
                        - 1002
                        - 1253.5
                        - 991
                        - '145.00'
                        - '145.00'
                        page: 0
                      - box:
                        - 803
                        - 1042
                        - 980
                        - 1063
                        - 891.5
                        - 1052.5
                        - Sales Tax 6.25%
                        - Sales Tax 6.25%
                        page: 0
                      - box:
                        - 1244
                        - 1042
                        - 1289
                        - 1065
                        - 1266.5
                        - 1053.5
                        - '9.06'
                        - '9.06'
                        page: 0
                      - box:
                        - 872
                        - 1104
                        - 981
                        - 1137
                        - 926.5
                        - 1120.5
                        - TOTAL
                        - TOTAL
                        page: 0
                      - box:
                        - 1172
                        - 1101
                        - 1289
                        - 1140
                        - 1230.5
                        - 1120.5
                        - "$ 154.06"
                        - "$ 154.06"
                        page: 0
                      - box:
                        - 102
                        - 1728
                        - 327
                        - 1760
                        - 214.5
                        - 1744
                        - Terms & Conditions
                        - Terms & Conditions
                        page: 0
                      - box:
                        - 104
                        - 1767
                        - 422
                        - 1801
                        - 263
                        - 1784
                        - Payment is due within 15 days
                        - Payment is due within 15 days
                        page: 0
                      - box:
                        - 104
                        - 1841
                        - 616
                        - 1871
                        - 360
                        - 1856
                        - 'Please make checks payable to: East Repair Inc.'
                        - 'Please make checks payable to: East Repair Inc.'
                        page: 0
                      Subtotal:
                        UICategory: VAT & Amounts
                        UIName: Subtotal
                        UIType: Amount
                        matches:
                        - keyword:
                          - 897
                          - 775
                          - 981
                          - 797
                          - 939
                          - 992
                          - Subtotal
                          - Subtotal
                          match: 145
                          matchmulti: '145.00'
                          page: 0
                          value:
                          - 1219
                          - 980
                          - 1288
                          - 1002
                          - 1253.5
                          - 991
                          - '145.00'
                          - '145.00'
                      Supplier: 
                      SwiftCode:
                        UICategory: Payment Instructions
                        UIName: Swift Code
                        UIType: Text
                        matches:
                        - keyword: 
                          match: 
                          matchmulti: 
                          page: 
                          value: 
                      TableDetected: true
                      Tables:
                      - GridX:
                        - 106
                        - 212
                        - 797
                        - 1002
                        - 1309
                        GridY:
                        - 775
                        - 833
                        - 895
                        - 958
                        GridYPages:
                        - 0
                        - 0
                        - 0
                        - 0
                        HeaderPage: 0
                        header:
                        - 120
                        - 720
                        - 1293
                        - 761
                        headernum: 4
                      TaxTotal:
                        UICategory: VAT & Amounts
                        UIName: Tax Total
                        UIType: Amount
                        matches:
                        - keyword:
                          - 803
                          - 836
                          - 980
                          - 857
                          - 891.5
                          - 1052.5
                          - Sales Tax 6.25%
                          - Sales Tax 6.25%
                          match: 6.2
                          matchmulti: Sales Tax 6.25%
                          page: 0
                          value:
                          - 803
                          - 1042
                          - 980
                          - 1063
                          - 891.5
                          - 1052.5
                          - Sales Tax 6.25%
                          - Sales Tax 6.25%
                      Total:
                        UICategory: VAT & Amounts
                        UIName: Total
                        UIType: Amount
                        matches:
                        - keyword:
                          - 872
                          - 898
                          - 981
                          - 931
                          - 926.5
                          - 1120.5
                          - TOTAL
                          - TOTAL
                          match: 154.06
                          matchmulti: "$ 154.06"
                          page: 0
                          value:
                          - 1172
                          - 1101
                          - 1289
                          - 1140
                          - 1230.5
                          - 1120.5
                          - "$ 154.06"
                          - "$ 154.06"
                      Type: invoice_image
                      URL:
                        UICategory: Vendor & Customer
                        UIName: URL
                        UIType: Text
                        matches:
                        - keyword: 
                          match: 
                          matchmulti: 
                          page: 
                          value: 
                      num_pages: 1
                    docId: 7650
                    status: COMPLETED
                status: Success

        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/unauthorized'
        '402':
          description: Payment Required
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentrequired'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/forbidden'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/notfound'
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidinput'                  
        '419':
          description: Input Field Missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputfieldmissing'
        '420':
          description: Input Limit Exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputlimitexceeded'        
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servererror'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gatewaytimeout'
      security:
        - APIAuthorizer: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/input'
        required: true              
components:
  schemas:
    success:
        type: object
        properties: 
          results:
            type: object
            example: { "<Json": "Object>" }
            description: The result of the API call
            properties:
              scandocuments: 
                type: object
                example: { "<Json": "Object>" }
                description: The details of documents
                properties:
                  docId:
                    type: integer
                    format: int32
                    example: 102581
                    description: Document ID
                  status:
                    type: string
                    example: COMPLETED
                    description: Status of staple API
                  data:
                    type: object
                    example: { "<Json": "Object>" }
                    description: The details scan document data
                    properties:
                      docsize:
                        type: array
                        example: [[1990,1490]]
                        description: An array contain the size info of template
                        items:
                          oneOf:
                            - type: number
                              example: 1990
                            - type: number
                              example: 1490  
                      num_pages:
                        type: integer
                        format: int32
                        example: 1
                        description: Total Pages
                      customer:
                        type: string
                        example: XYZ Buyer
                        description: Customer Name
                      supplier:
                        type: string
                        example: ABC Supplier
                        description: Supplier Name                        
                      type:
                        type: string
                        example: receipt
                        description: Type of Document     
                      tabledetected:
                        type: boolean
                        example: True
                        description: True if table detected 
                      total:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Invoice Total Amount     
                      subtotal:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Sub-Total
                      taxtotal:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Tax Total 
                      servicecharge:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Service Charge     
                      currency:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Currency  
                      billingdddress:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Billing Address  
                      email:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Email 
                      url:
                        type: object
                        example: { "<Json": "Object>" }
                        description: URL 
                      uennumber:
                        type: object
                        example: { "<Json": "Object>" }
                        description: UEN Number
                      gstnumber:
                        type: object
                        example: { "<Json": "Object>" }
                        description: GST Number     
                      senderaddress:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Sender Address     
                      otherdate:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Other Date   
                      lineitems_standardheader:
                        type: object
                        example: { "<Json": "Object>" }
                        description: Line items standard header                          
          message:
            type: string
            example: Successfully Processed
            description: Description of the API status
          status:
            type: string
            example: Success
            description: The status of the API call - success/failure 
    unauthorized:
      type: object
      properties:
        message:
          type: string
          example: Missing Authentication Token
        status:
          type: string
          example: Failure
    forbidden:
      type: object
      properties:
        message:
          type: string
          example: Access Denied Unauthorized User
        status:
          type: string
          example: Failure
    paymentrequired:
      type: object
      properties:
        message:
          type: string
          example: Insufficient Credits Kindly Top Up
        status:
          type: string
          example: Failure
    notfound:
      type: object
      properties:
        message:
          type: string
          example: Invalid Request URL
        status:
          type: string
          example: Failure
    servererror:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status:
          type: string
          example: Failure
    gatewaytimeout:
      type: object
      properties:
        message:
          type: string
          example: Request Timeout
        status:
          type: string
          example: Failure
    inputfieldmissing:
      type: object
      properties:
        message:
          type: string
          example: Input Field Missing
        status:
          type: string
          example: Failure
    inputlimitexceeded:
      type: object
      properties:
        message:
          type: string
          example: Input Limit Exceeded
        status:
          type: string
          example: Failure
    versions:
      type: object
      properties: 
        v0.2.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Sep 05, 2022
              x-details: Initial version release
              description: Bug Fixed      
        v0.1.0:
         type: array
         items:
          oneOf:
            - type: string
              example: Published Date - Aug 11, 2021
              x-details: Initial version release
              description: Latest Version
    input:
      type: object
      required:
        - file
      properties:
        file:
          type: string
          format: binary
          default: true
          example:  upload file
          description: The file path that describes the location of the receipt document.
        handwritten:
          type: boolean
          example:  'false'
          description: Specify handwritten true or false. Default is false       
  securitySchemes:
    APIAuthorizer:
      type: apiKey
      name: x-api-key
      in: header
      x-amazon-apigateway-authtype: custom
      description: Authentication is done using the x-api-key in the request header
